### ISSUE TITLE
Extension fails to compile on ruby 2.0.0p0

### ISSUE THREAD

**Issue by Nerian** [tmm1/rblineprof#15]
Gem does not compile on ruby 2.0.0p0

Ruby 2.0.0p0

```
➜  ~  ruby -v
ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-darwin12.2.1]
➜  ~  gem install rblineprof
Upgraded http://rubygems.org/ to HTTPS
Fetching: rblineprof-0.2.7.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing rblineprof:
    ERROR: Failed to build gem native extension.

    /Users/Nerian/.rvm/rubies/ruby-2.0.0-p0/bin/ruby extconf.rb
Upgraded http://rubygems.org/ to HTTPS
checking for vm_core.h... no
checking for vm_core.h... no
checking for vm_core.h... yes
checking for iseq.h... yes
creating Makefile

make
compiling rblineprof.c
rblineprof.c: In function ‘stackframe_record’:
rblineprof.c:136: warning: ISO C90 forbids mixed declarations and code
rblineprof.c: In function ‘profiler_hook’:
rblineprof.c:271: error: ‘rb_iseq_t’ has no member named ‘filepath’
rblineprof.c:272: error: ‘rb_iseq_t’ has no member named ‘filepath’
rblineprof.c:274: error: ‘rb_iseq_t’ has no member named ‘filename’
rblineprof.c:220: warning: unused variable ‘curr_srcfile’
rblineprof.c: In function ‘cleanup_files’:
rblineprof.c:347: warning: ISO C90 forbids mixed declarations and code
rblineprof.c: In function ‘summarize_files’:
rblineprof.c:363: warning: ISO C90 forbids mixed declarations and code
rblineprof.c: In function ‘lineprof’:
rblineprof.c:392: warning: ISO C90 forbids mixed declarations and code
rblineprof.c:430: warning: ISO C90 forbids mixed declarations and code
rblineprof.c:434: warning: ISO C90 forbids mixed declarations and code
rblineprof.c:435: warning: unused variable ‘ary’
make: *** [rblineprof.o] Error 1


Gem files will remain installed in /Users/Nerian/.rvm/gems/ruby-2.0.0-p0/gems/rblineprof-0.2.7 for inspection.
Results logged to /Users/Nerian/.rvm/gems/ruby-2.0.0-p0/gems/rblineprof-0.2.7/ext/gem_make.out
➜  ~  cat /Users/Nerian/.rvm/gems/ruby-2.0.0-p0/gems/rblineprof-0.2.7/ext/gem_make.out 
/Users/Nerian/.rvm/rubies/ruby-2.0.0-p0/bin/ruby extconf.rb
Upgraded http://rubygems.org/ to HTTPS
checking for vm_core.h... no
checking for vm_core.h... no
checking for vm_core.h... yes
checking for iseq.h... yes
creating Makefile

make
compiling rblineprof.c
rblineprof.c: In function ‘stackframe_record’:
rblineprof.c:136: warning: ISO C90 forbids mixed declarations and code
rblineprof.c: In function ‘profiler_hook’:
rblineprof.c:271: error: ‘rb_iseq_t’ has no member named ‘filepath’
rblineprof.c:272: error: ‘rb_iseq_t’ has no member named ‘filepath’
rblineprof.c:274: error: ‘rb_iseq_t’ has no member named ‘filename’
rblineprof.c:220: warning: unused variable ‘curr_srcfile’
rblineprof.c: In function ‘cleanup_files’:
rblineprof.c:347: warning: ISO C90 forbids mixed declarations and code
rblineprof.c: In function ‘summarize_files’:
rblineprof.c:363: warning: ISO C90 forbids mixed declarations and code
rblineprof.c: In function ‘lineprof’:
rblineprof.c:392: warning: ISO C90 forbids mixed declarations and code
rblineprof.c:430: warning: ISO C90 forbids mixed declarations and code
rblineprof.c:434: warning: ISO C90 forbids mixed declarations and code
rblineprof.c:435: warning: unused variable ‘ary’
make: *** [rblineprof.o] Error 1
➜  ~  
```

Ruby 1.9.3p392

```
➜  ~  ruby -v
ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin12.2.1]
➜  ~  gem install rblineprof                                                                      
Fetching: rblineprof-0.2.7.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rblineprof-0.2.7
1 gem installed
```
